openapi: 3.0.0
info:
  title: Advanced URL Shortener API
  description: An API for shortening URLs with analytics, custom aliases, and Google Sign-In authentication.
  version: 1.0.0
servers:
  - url: "http://localhost:5000/api"
    description: Local development server
components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: connect.sid
  schemas:
    Url:
      type: object
      properties:
        shortUrl:
          type: string
          example: "http://localhost:5000/myalias"
        longUrl:
          type: string
          example: "https://example.com"
        alias:
          type: string
          example: "myalias"
        topic:
          type: string
          example: "Tech"
    AnalyticsResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        totalClicks:
          type: integer
          example: 120
        uniqueUsers:
          type: integer
          example: 80
        clicksByDate:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
                example: "2025-02-01"
              clicks:
                type: integer
                example: 15
        osType:
          type: array
          items:
            type: object
            properties:
              osName:
                type: string
                example: "Windows"
              uniqueClicks:
                type: integer
                example: 50
              uniqueUsers:
                type: integer
                example: 40
        deviceType:
          type: array
          items:
            type: object
            properties:
              deviceName:
                type: string
                example: "Mobile"
              uniqueClicks:
                type: integer
                example: 70
              uniqueUsers:
                type: integer
                example: 55
paths:
  /auth/google:
    get:
      summary: Google OAuth authentication
      operationId: googleAuth
      responses:
        302:
          description: Redirect to Google login

  /auth/google/callback:
    get:
      summary: Google OAuth callback
      operationId: googleCallback
      responses:
        200:
          description: User logged in successfully

  /url/shorten:
    post:
      summary: Shorten a URL
      description: Takes a long URL and returns a shortened version.
      security:
        - CookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
                  example: "https://example.com"
                customAlias:
                  type: string
                  example: "myalias"
                topic:
                  type: string
                  example: "Tech"
      responses:
        200:
          description: Successfully shortened the URL
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Url"
        400:
          description: Invalid input

  /url/{alias}:
    get:
      summary: Redirect to the original URL
      description: Retrieves the long URL from the alias and redirects the user.
      parameters:
        - name: alias
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved long URL
        404:
          description: Short URL not found

  /analytics/alias/{alias}:
    get:
      summary: Get analytics for a specific short URL
      description: Retrieves click statistics, unique visitors, and usage patterns for a given short URL alias.
      parameters:
        - name: alias
          in: path
          required: true
          schema:
            type: string
          example: "abc123"
      responses:
        200:
          description: Successful response with analytics data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnalyticsResponse"
        404:
          description: Short URL not found
        500:
          description: Server error

  /analytics/topic/{topic}:
    get:
      summary: Get analytics for URLs under a specific topic
      description: Fetches analytics data for all URLs associated with a given topic.
      parameters:
        - name: topic
          in: path
          required: true
          schema:
            type: string
          example: "tech-news"
      responses:
        200:
          description: Successful response with analytics data
        404:
          description: No URLs found for this topic
        500:
          description: Server error

  /analytics/overall:
    get:
      summary: Get overall analytics for the authenticated user
      description: Retrieves aggregated analytics data for all URLs created by the authenticated user.
      security:
        - CookieAuth: []
      responses:
        200:
          description: Successful response with overall analytics data
        404:
          description: No URLs found for this user
        500:
          description: Server error
